# Generated by Django 4.1.3 on 2022-12-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='worda',
            new_name='section',
        ),
    ]
