# Generated by Django 4.1.3 on 2022-12-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_worda_staff_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
