# Generated by Django 4.1.3 on 2023-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_ward10_ward11_ward12_ward2_ward3_ward4_ward5_ward6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gazette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('document', models.CharField(max_length=80)),
                ('date', models.DateField()),
            ],
        ),
    ]
