# Generated by Django 4.1.3 on 2023-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_gazette_document_alter_gazette_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazette',
            name='document',
            field=models.CharField(max_length=1000),
        ),
    ]
