# Generated by Django 4.1.3 on 2023-01-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='news',
        ),
    ]
