# Generated by Django 4.1.3 on 2023-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_text_news_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.TextField()),
                ('document', models.TextField()),
            ],
        ),
    ]
