# Generated by Django 4.1.3 on 2023-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('document', models.CharField(max_length=700)),
                ('date', models.DateField()),
            ],
        ),
    ]
