# Generated by Django 4.1.3 on 2023-01-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_annualpr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipald',
            old_name='name',
            new_name='title',
        ),
    ]
